In [8]:
import numpy as np
import pandas as pd

data = {
    'Maths': [80, 90, 85, 95, 70],
    'Science': [75, 85, 80, 90, 65],
    'English': [70, 88, 78, 92, 60]
}

df = pd.DataFrame(data)
print(df)

X = df.values
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_std = (X - mean) / std

cov_matrix = np.cov(X_std.T)
print("Covariance Matrix:\n", cov_matrix)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

principal_components = eigenvectors[:, :2]

pca_data = X_std.dot(principal_components)
print("PCA Transformed Data:\n", pca_data)

   Maths  Science  English
0     80       75       70
1     90       85       88
2     85       80       78
3     95       90       92
4     70       65       60
Covariance Matrix:
 [[1.25       1.25       1.23812521]
 [1.25       1.25       1.23812521]
 [1.23812521 1.23812521 1.25      ]]
Eigenvalues:
 [3.73417537e+00 9.95551045e-17 1.58246323e-02]
Eigenvectors:
 [[-5.77964217e-01 -7.07106781e-01 -4.07378649e-01]
 [-5.77964217e-01  7.07106781e-01 -4.07378649e-01]
 [-5.76120410e-01 -7.81630796e-15  8.17364835e-01]]
PCA Transformed Data:
 [[ 0.91207006 -0.15256888]
 [-1.31881901  0.1589292 ]
 [-0.15408839 -0.06674396]
 [-2.18783311 -0.03494237]
 [ 2.74867044  0.09532602]]
